export const Alumini2024 = [
  {
    name: "Vinay Gottimukkala",
    role: "President",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/1.jpg",
  },
  {
    name: "Asritha Morampudi",
    role: "Treasurer",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/2.jpg",
  },
  {
    name: "G Venkata Siva Praveen",
    role: "Campus Relations",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/3.jpg",
  },
  {
    name: "Yogindra Kanumuri",
    role: "Campus Relations",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/4.jpg",
  },
  {
    name: "Lalith Madhav K",
    role: "Designing",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/5.jpg",
  },
  {
    name: "S Anudeep",
    role: "Designing",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/6.jpg",
  },
  {
    name: "M Jaswitha Priya",
    role: "Drafting",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/7.jpg",
  },
  {
    name: "T Hruday",
    role: "Drafting",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/8.jpg",
  },
  {
    name: "Sk Rabbani",
    role: "Technical clubs",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/9.jpg",
  },
  {
    name: "Santosh Kumar E",
    role: "Technical",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/10.jpg",
  },
  {
    name: "Namgiri Snehith",
    role: "Technical",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/11.jpg",
  },
  {
    name: "B Likitha",
    role: "Non-Technical",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/12.jpg",
  },
  {
    name: "V Pragnesh Ram",
    role: "Non-Technical",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/13.jpg",
  },
  {
    name: "B L Gnapikaa",
    role: "HR & INFO COMM",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/14.jpg",
  },
  {
    name: "Y Deepika Jyothi",
    role: "HR & INFO COMM",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/15.jpg",
  },
  {
    name: "G N V Surya",
    role: "Creative Arts",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/16.jpg",
  },
  {
    name: "T Nagamani",
    role: "Creative Arts",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/17.jpg",
  },
  {
    name: "G Pavan Teja",
    role: "Public Relations",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/18.jpg",
  },
  {
    name: "K B Varun Krishna",
    role: "Public Relations",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/19.jpg",
  },
  {
    name: "JITENDRA SAI KARTHIK J",
    role: "R&C",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/20.jpg",
  },
  {
    name: "Teja Sri.Chaparala",
    role: "R&C",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/21.jpg",
  },
  {
    name: "Kowshik Reddy",
    role: "Logistics",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/22.jpg",
  },
  {
    name: "Veera Bolloju",
    role: "Logistics",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/23.jpg",
  },
  {
    name: "Akarsh",
    role: "Sponsorship",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/24.jpg",
  },
  {
    name: "Disney pardhasaradhi",
    role: "Sponsorship",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/25.jpg",
  },
  {
    name: "M INDU CHOWDARY",
    role: "Protocol",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/26.jpg",
  },
  {
    name: "B DAMODHAR RAO",
    role: "Protocol",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/27.jpg",
  },
  {
    name: "M Sai Bhavana",
    role: "Culturals",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/28.jpg",
  },
  {
    name: "K CHANDU MANI SAI",
    role: "Culturals",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/29.jpg",
  },
  {
    name: "N YASWANTH GIRI",
    role: "Stage Management",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/30.jpg",
  },
  {
    name: "RAJARIKAM KIREETI",
    role: "Stage Management",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/31.jpg",
  },
  {
    name: "CHAPARALA LEKHANA",
    role: "Anchoring",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/32.jpg",
  },
  {
    name: "A.V.N NITHIN DATTA",
    role: "Hospitality",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/33.jpg",
  },
  {
    name: "SHAIK ALTHAF HUSSAIN",
    role: "Hospitality",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/34.jpg",
  },
  {
    name: "B RISHI KIRAN",
    role: "Broad Casting",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/35.jpg",
  },
  {
    name: "K Haveela",
    role: "Extension & Outreach Activites",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/36.jpg",
  },
  {
    name: "DJYOSWITHA SINDHU",
    role: "Extension & Outreach Activites",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/37.jpg",
  },
  {
    name: "Karthik Chowdary",
    role: "Secretary",
    linkedin: "",
    instagram: "",
    email: "",
    phonenumber: "+9193961330",
    image: "/img/38.jpg",
  },
];
export const Alumini2022 = [];
export const Alumini2023 = [];
